const express = require('express')
const app = express()
const userRouter = require('./routes/user.route')
const authRouter = require('./routes/auth.route')
require('./db/connect')
app.use(express.json())
app.use('/api/user',userRouter)
app.use('/api/auth',authRouter)

app.listen(4444,console.log('server is listening on port 4444...'))